#!/bin/bash
set -x -e -o pipefail

TAG=$(git describe --match='v*' --exact-match 2>/dev/null)
if ! test "$TAG"; then
	echo "no tag to release"
	exit 1
fi

mkdir -p bin

CGO_ENABLED=0 go get -v -installsuffix static
CGO_ENABLED=0 go build -v -installsuffix static \
	-ldflags "-X 'main.ver=$TAG'" \
	-o bin/${PWD##*/}-`uname -s`-`uname -m`

GH="${PWD##*/github.com/}"
ghr -u "${GH%%/*}" -r "${GH##*/}" -replace "$TAG" bin
